version: '3'

services:
  dotnet_api:
    build: .
    ports:
      - 7080:7080
    depends_on: 
      - adminer
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./MySQL/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3307

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on: 
      - db